DATA:
  CLASS_INDICES_OLD: [0, 1, 2, 3, 4, 5, 6]
  CLASS_INDICES_NEW: [7,8,9]
  CLASS_INDICES_ALL: [0,1,2,3,4,5,6,7,8,9]

MODEL:
  OLD_CHECKPOINT: "results/baseline/best_model_baseline.pth"

TRAIN:
  EPOCHS: 50
  BATCH_SIZE: 64
  
OPTIMIZER:
  LR: 0.1 # was 0.07
  WEIGHT_DECAY: 0.0
  MOMENTUM: 0.0

SCHEDULER:
  USE: true 
  MIN_LR: 1.0e-6

EARLY_STOPPING:
  USE: true
  PATIENCE: 8
  THRESHOLD: 0.0005
  MODE: "min"
  BEST_OUTPUT_NAME: "best_model_control_once_global_0.1_effective_lr_mean_factor_beta"

LRP:
  MODE: "once"
  # falls normalize --> true, ohne Normalisierung false
  NORMALIZE: true
  BETA_QUANTILE: 0.99
  BETA_SCOPE: "global"  # "global" oder "local"

OUTPUT:
  NAME: "baseline_control_lrp_once_global"
  DIR: "results_experiments/baseline_control_lrp_once_global_0.1_effective_lr_mean_factor_beta"  # falls bet local --> _local_beta, sonst dynamic_beta
  NEURON_RELEVANCE: "relevance_values_control_lrp_once_global.pt"
  LOSS_PLOT_NEW: "loss_curve_new_control_lrp_once_global"
  LOSS_PLOT_OLD_NEW_ALL: "loss_curve_old_new_all_control_lrp_once_global"
  CM_NAME_OLD: "confusion_matrix_old_control_lrp_once_global"
  CM_NAME_NEW: "confusion_matrix_new_control_lrp_once_global"
  CM_NAME_ALL: "confusion_matrix_all_control_lrp_once_global"



